#!/bin/bash
# Clean generated datasets and training outputs from auto_train.sh.
#
# Usage:
#   bash clean_generated.sh        # preview only
#   bash clean_generated.sh --yes  # delete generated files
#   bash clean_generated.sh --name yolo_ui_custom --yes

set -euo pipefail

NAME="yolo_ui"
YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --name)
            NAME="${2:-}"
            shift 2
            ;;
        --yes)
            YES=true
            shift
            ;;
        -h|--help)
            cat <<'EOF'
Usage:
  bash clean_generated.sh        # preview only
  bash clean_generated.sh --yes  # delete generated files
  bash clean_generated.sh --name yolo_ui_custom --yes
EOF
            exit 0
            ;;
        *)
            echo "Unknown arg: $1" >&2
            exit 1
            ;;
    esac
done

if [[ -z "$NAME" || ! "$NAME" =~ ^[A-Za-z0-9_.-]+$ ]]; then
    echo "Invalid --name: '$NAME'" >&2
    echo "Only letters, numbers, underscore, dot, and dash are allowed." >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

targets=()

add_if_exists() {
    local path="$1"
    if [[ -e "$path" ]]; then
        targets+=("$path")
    fi
}

# Synthetic datasets generated by Smoke Test and formal training.
add_if_exists "dataset_smoke"
add_if_exists "dataset"

# Training/export outputs from auto_train.sh (project=runs, name=$NAME).
add_if_exists "runs/${NAME}_smoke"
add_if_exists "runs/${NAME}"

# Compatibility for older Ultralytics default project layout.
add_if_exists "runs/detect/${NAME}_smoke"
add_if_exists "runs/detect/${NAME}"

echo "Project: $SCRIPT_DIR"
echo "Run name: $NAME"
echo ""

if [[ ${#targets[@]} -eq 0 ]]; then
    echo "No generated dataset/training outputs found."
    exit 0
fi

echo "Generated paths to remove:"
for target in "${targets[@]}"; do
    echo "  - $target"
done

if [[ "$YES" != true ]]; then
    echo ""
    echo "Preview only. Re-run with --yes to delete these paths."
    exit 0
fi

echo ""
for target in "${targets[@]}"; do
    echo "Removing $target"
    rm -rf -- "$target"
done

echo ""
echo "Clean complete. You can now run: bash auto_train.sh"
